BillPayWebApplication/Controllers/PatientPortalController.cs
using BillPayData.Models;
using Microsoft.AspNetCore.Mvc;
using BillPayData.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Options;
using BillPayData.Models.Settings;

namespace BillPayWebApplication.Controllers
{
    public class PatientPortalController : Controller
    {

        private IBillingData db;
        private readonly IOptions<MySettingsModel> appSettings;

        public PatientPortalController(IBillingData db, IOptions<MySettingsModel> app)
        {
            this.db = db;
            this.appSettings = app;
            
            
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();

        }

        [Authorize]
        [HttpGet]
        public IActionResult Alerts()
        {
            return PartialView("~/Views/Shared/_Alerts.cshtml");
        }

        [Authorize]
        [HttpGet]
        public IActionResult BillingSearch()
        {
           
            return PartialView("~/Views/Shared/_BillingLookupSearch.cshtml");
        }


        [HttpPost]
        public IActionResult BillingDetails(string BillingID, string AccountNumber)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("~/Views/Shared/_BillingNotFound.cshtml"); // bill not found
            }


            BillInformation billInfo = db.GetBill(BillingID,AccountNumber);

            if (billInfo == null)
            {
                return PartialView("~/Views/Shared/_BillingNotFound.cshtml");//Bill not found
            }

            return PartialView("~/Views/Shared/_BillingDetails.cshtml", billInfo);

        }


     
    }
}

BillPayWebApplication/Controllers/PaymentsController.cs
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using BillPayData.Models;
using BillPayData.Services;
using System.Configuration;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using BillPayData.Models.Settings;

namespace BillPayWebApplication.Controllers
{
    public class PaymentsController : Controller
    {
        private IBillingData db;
        private IOptions<MySettingsModel> appSettings;

        

        public PaymentsController(IBillingData db, IOptions<MySettingsModel> app)
        {
            this.appSettings = app;
            StripeConfiguration.ApiKey = this.appSettings.Value.StripeApiSecret;
            
            this.db = db;
        }

        [HttpPost]
        public IActionResult Create(string BillingID, string AccountNumber)
        {

            var domain = "https://rdgbillingapp.azurewebsites.net/";

            BillInformation billInfo = db.GetBill(BillingID, AccountNumber);

            if (billInfo == null)
            {
                return PartialView("~/Views/Shared/_BillingNotFound.cshtml");
            }

            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions

                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (int)(billInfo.Amount * 100), //translates bill amount to pennies for stripe
                            Currency = "usd",

                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = "Medical Bill",
                            },
                        },
                        Quantity = 1,
                    },
                },

                PaymentIntentData = new SessionPaymentIntentDataOptions
                {
                    //This metadata is sent to the checkout session and hooked back into the application in StripeWebHookController after the bill succeeds or fails
                    Metadata = new Dictionary<string, string>
                    {
                        { "BillingID", billInfo.BillingID },
                        { "AccountNumber", billInfo.AccountNumber }
                    }
                },

                Mode = "payment",

                SuccessUrl = domain + "/Success",
                CancelUrl = domain + "/Failed",
        };

        var service = new SessionService();

        Session session = service.Create(options);

        Response.Headers.Add("Location", session.Url);

        return new StatusCodeResult(303); //retuns the stripe checkout session created


        }
    }
}

BillPayWebApplication/Views/Shared/_Alerts.cshtml
@{
    Layout = null;
}

<h2>No Alerts at this time!</h2>

BillPayWebApplication/Views/Shared/_BillingDetails.cshtml
@model BillPayData.Models.BillInformation

@{
    Layout = null;
}

<head>


</head>

<h3>Bill Details</h3>

<body>
    <form asp-action="Create" asp-controller="Payments" asp-method="post">

        <div>
        <table class="table table-dark table-bordered table-hover table-responsive">
            <tr>
                <th></th>
                <th>BillingID</th>
                <th>Account Number</th>
                <th>Provider</th>
                <th>Amount</th>
                <th>Status</th>
            </tr>
            <tbody class="table">
                <tr>
                    <td>
                        <i class="bx bxs-plus-circle bx-tada" id="PlusMinus"></i>

                        <div style="display:none" id="hiddenTable">
                            <table cellpadding="0" cellspacing="0" class="ChildGrid">
                                <tr>
                                    <th>Date Of Service:</th>
                                </tr>
                                <tr>
                                    <td>@Model.VisitInformation.DateOfService</td>
                                </tr>
                            </table>
                            <table cellpadding="0" cellspacing="0" class="ChildGrid">
                                <tr>
                                    <th>Location:</th>
                                </tr>
                                <tr>
                                    <td>Location Name: @Model.VisitInformation.Location.LocationName</td>     
                                </tr>
                                <tr>
                                     <td>Location Address: @Model.VisitInformation.Location.LocationAddress</td>
                                </tr>
                               
                            </table>
                            <table cellpadding="0" cellspacing="0" class="ChildGrid">
                                <tr>
                                    <th>Visit Type:</th>
                                </tr>
                                <tr>
                                    <td>Type: @Model.VisitInformation.VisitType.Type</td>
                                </tr>
                            </table>
                            <table cellpadding="0" cellspacing="0" class="ChildGrid">
                                <tr>
                                    <th>Provider:</th>
                                </tr>
                                <tr>
                                    <td>Name: @Model.VisitInformation.Provider.ProviderName</td>
                                </tr>
                                <tr>
                                    <td>Speciality: @Model.VisitInformation.Provider.Speciality.SpecialityName</td>
                                </tr>
                            </table>
                        </div>
                    </td>
                    <input type="hidden" asp-for="BillingID" />
                    <td>@Model.BillingID</td>
                    <input type="hidden" asp-for="AccountNumber" />
                    <td>@Model.AccountNumber</td>
                    <td>@Model.VisitInformation.Provider.ProviderName</td>
                    <td>@Model.Amount</td>
                    <td>@Model.PayStatus</td>
                </tr>
            </tbody>
        </table>

        @if (Model.PayStatus == "Unpaid")
        {
            <input type="submit" value="Pay Bill" id="PayBill" >
        }

    </div>

    </form>
    

    <script type="text/javascript" src="~/js/PatientPortal/Billing Details/PlusMinus.js"></script>


    <script>

$(document).ready(function() {

    //Displays the hidden table with additional information and switches icon between plus and minus
    OnPlusMinusClick();

})

 

    </script>



</body>

BillPayWebApplication/Views/Shared/_BillingLookupSearch.cshtml
@model BillPayData.Models.BillInformation

@{
    Layout = null;
}

<head>
    <link href="~/css/PatientPortal/BillingSearch/TextboxStyling.css" rel="stylesheet" />
    
</head>

<h2>Bill Lookup System</h2>
<p>To find your bill:<br /></p>
<p>Please enter the information below exactly as it appears on your bill!</p>

<body>

    <div class="form-group row">
     <input asp-for="BillingID" class="form-control TextBox" type="text" placeholder="Billing Number" id="BillingID">
    </div>

    <div class="form-group row">
     <input asp-for="AccountNumber" class="form-control TextBox" type="text" placeholder="Account Number" id="AccountNumber" />
    </div>
   
    <div class="form-group">
        <input type="button" value="Find My Bill" id="FindBill"/>
    </div>
   

     <div id="billOutput">
         
    </div>



<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script type="text/javascript">
$(function() {
    $("#FindBill").click(function() {


        $.ajax({
            type: 'POST',
            url: '@Url.Action("BillingDetails","PatientPortal")',
            data: {'BillingID' : $('#BillingID').val(), 'AccountNumber' : $('#AccountNumber').val()},
            success: function(partialView) {
                $('#billOutput').html(partialView);
            }
         
        })
    })
})

</script>

</body>

BillPayWebApplication/Views/Shared/_BillingNotFound.cshtml
@{
    Layout = null;
}

<h2>Bill not found in our systems</h2>
<p>Please ensure that the information is entered as it apperas on your bill</p>

BillPayWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BillPayWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BillPayWebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BillPayWebApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BillPayWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BillPayWebApplication/Views/Shared/_PatientPortalLayout.cshtml
@{
}

<!doctype html>
<html lang="en">

    <head>
        <link href="~/css/PatientPortal/Layout/SideBarStyling.css" rel="stylesheet" />
        <link id="sidebar" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" rel="stylesheet" />
        <link href="~/css/PatientPortal/Layout/PartialPageInsertArea.css" rel="stylesheet" />
        <link href="~/css/PatientPortal/Layout/NavLinkStyling.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

    </head>

    
<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle">
            <i class='bx bx-menu' id="header-toggle"></i>
        </div>
        <partial name="_LoginPartial"/>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Patient Portal</span> </a>
               
                <a href="#" class="nav_link" id="Alerts"> <i class='bx bx-building-house nav_icon'></i> <span class="nav_name">Alerts</span> </a>
                 <a href="#" class="nav_link" id="Billing"> <i class='bx bx-building-house nav_icon'></i> <span class="nav_name">Billing</span> </a>
                        
               
            </div>
            <a href="@Url.Action("Index", "Home")" class="nav_link"> <i class='bx bx-building-house nav_icon'></i> <span class="nav_name">Back To Home</span> </a>
            @*<a href="#" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span> </a>*@
        </nav>
    </div>

    <!--handles all of the events pertaining to opening, closing, and changing the active nav link-->
    <script src="~/js/PatientPortal/Layout/SideBarEventHandler.js"></script>
    

    <div>
        @RenderBody()
    </div>

    <div id="insert">
        
    </div>

     <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

     <script type="text/javascript">
$(function() {
    $('#Alerts').click(function() {
        
        $.ajax({
            url: '@Url.Action("Alerts","PatientPortal")',
            type: 'GET',           
            success: function(partialView) {
                $('#insert').html(partialView);
            }
        })
    })
})

     </script>

     <script type="text/javascript">
         $(function() {
    $('#Billing').click(function() {
     
        $.ajax({
            url: '@Url.Action("BillingSearch","PatientPortal")',
            type: 'GET',           
            success: function(partialView) {
                $('#insert').html(partialView);
            }
        })
    })
})
     </script>

     @await RenderSectionAsync("Scripts", required: false)

    </body>


</html>